### ISSUE TITLE
Check if HTTP compression is enabled for large files

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/discovery-service-frontend#37] opened 2018-08-15 09:40 UTC
The old discovery service leads to a download of 837 KB in total, the new one to 1.79 MB. As far as I can see, for none of the files the Content-encoding: gzip is returned by the HTTP server. This was the case for the old one. Would be good to optimize this before putting the new discovery service into production.

**Comment by andmor-** [comment] 2018-08-15 15:28
The problem seems to be fixed by adding following to the nginx config file inside the image (`/etc/nginx/conf.d/discovery.conf`) under the `server` context

```   
    gzip              on;
    gzip_disable      "msie6";
    gzip_proxied      any;
    gzip_http_version 1.0;
    gzip_vary         on;
    gzip_min_length   200;
    gzip_buffers      16 8k;
    gzip_types        text/plain
                      text/xml
                      text/css
                      text/comma-separated-values
                      text/javascript
                      application/javascript
                      application/x-javascript
                      application/atom+xml
                      application/json
                      application/xml;
```

**Comment by WillemElbers** [comment] 2018-08-20 10:52
Confirmed that compression is now enabled.

**Comment by andmor-** [comment] 2018-08-20 15:39
Is the change persistent? 
I did not figure out how to persist the change.

**Comment by WillemElbers** [comment] 2018-08-21 08:26
As @andmor mentioned this has to be included in the nginx serving the static javascript: https://gitlab.com/CLARIN-ERIC/docker-aai-discovery/tree/new

**Comment by WillemElbers** [comment] 2018-08-31 08:31
Now added in https://gitlab.com/CLARIN-ERIC/docker-aai-discovery/commit/341d3d5d4f74d3f79a013f7e1ba6127a673a825b

**Closed by WillemElbers** 2018-08-31 08:31 UTC
